if(CONFIG_PICOLIBC_IO_FLOAT)
        set(__IO_DEFAULT "d")
        set(__IO_FLOAT ON)
        set(__IO_LONG_LONG ON)
    elseif(CONFIG_PICOLIBC_IO_LONG_LONG)
        set(__IO_DEFAULT "l")
        set(__IO_FLOAT OFF)
        set(__IO_LONG_LONG ON)
    elseif(CONFIG_PICOLIBC_IO_MINIMAL)
        set(__IO_DEFAULT "m")
        set(__IO_FLOAT OFF)
        set(__IO_LONG_LONG OFF)
    else()
        set(__IO_DEFAULT "i")
        set(__IO_FLOAT OFF)
        set(__IO_LONG_LONG OFF)
    endif()

    if(CONFIG_PICOLIBC_IO_FLOAT_EXACT)
        set(__IO_FLOAT_EXACT ON)
    else()
        set(__IO_FLOAT_EXACT OFF)
    endif()

    if(CONFIG_PICOLIBC_IO_C99_FORMATS)
        set(__IO_C99_FORMATS ON)
    else()
        set(__IO_C99_FORMATS OFF)
    endif()

    if(CONFIG_PICOLIBC_IO_PERCENT_B)
        set(__IO_PERCENT_B ON)
    else()
        set(__IO_PERCENT_B OFF)
    endif()

    if(CONFIG_PICOLIBC_ASSERT_VERBOSE)
        set(__ASSERT_VERBOSE ON)
    else()
        set(__ASSERT_VERBOSE OFF)
    endif()

    if(CONFIG_PICOLIBC_FAST_STRCMP)
        set(__FAST_STRCMP ON)
    else()
        set(__FAST_STRCMP OFF)
    endif()

    if(CONFIG_PICOLIBC_NANO_MALLOC)
        set(__NANO_MALLOC ON)
    else()
        set(__NANO_MALLOC OFF)
    endif()

    if(CONFIG_PICOLIBC_PREFER_SIZE)
        set(__PREFER_SIZE_OVER_SPEED ON)
    else()
        set(__PREFER_SIZE_OVER_SPEED OFF)
    endif()

    if(CONFIG_PICOLIBC_MULTITHREAD)
        set(__SINGLE_THREAD OFF)
        set(__THREAD_LOCAL_STORAGE ON)
        set(__THREAD_LOCAL_STORAGE_API 1)
        set(__GLOBAL_ERRNO OFF)
    else()
        set(__SINGLE_THREAD ON)
        set(__THREAD_LOCAL_STORAGE OFF)
        set(__THREAD_LOCAL_STORAGE_API 0)
        if(CONFIG_PICOLIBC_GLOBAL_ERRNO)
            set(__GLOBAL_ERRNO ON)
        else()
            set(__GLOBAL_ERRNO OFF)
        endif()
    endif()

    # Fixed options for bare-metal
    set(__TINY_STDIO         ON)
    set(__INIT_FINI_ARRAY    1)
    set(__PICOCRT_ENABLE_MMU 0)
    set(__SEMIHOST           0)

add_subdirectory(../picolibc picolibc)
